create table if not exists public.vibes (
  id bigint generated by default as identity primary key,
  prompt text not null,
  image text not null,
  created_at timestamptz default now()
);

alter table public.vibes enable row level security;

create policy "Public read vibes"
on public.vibes for select
using (true);

create policy "Public insert vibes"
on public.vibes for insert
with check (true);
